version: '3.4'
services:
  spark-master:
    restart: always
    image: docker.mirrors.sjtug.sjtu.edu.cn/bde2020/spark-master:3.0.1-hadoop3.2
    network_mode: host
    environment:
      - INIT_DAEMON_STEP=setup_spark

  spark-worker-0:
    restart: always
    build: ./spark-worker
    network_mode: host
    environment:
      - "SPARK_MASTER=spark://node-master.lan:7077"

  spark-worker-1:
    restart: always
    build: ./spark-worker
    network_mode: host
    environment:
      - "SPARK_MASTER=spark://node-master.lan:7077"

  spark-worker-2:
    restart: always
    build: ./spark-worker
    network_mode: host
    environment:
      - "SPARK_MASTER=spark://node-master.lan:7077"


  hadoop-datanode-0:
    image: docker.mirrors.sjtug.sjtu.edu.cn/bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    restart: always
    network_mode: host
    volumes:
      - ./hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "node-master.lan:9870"
    env_file:
      - ./hadoop.env

  hadoop-datanode-1:
    image: docker.mirrors.sjtug.sjtu.edu.cn/bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    restart: always
    network_mode: host
    volumes:
      - ./hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "node-master.lan:9870"
    env_file:
      - ./hadoop.env

  hadoop-datanode-2:
    image: docker.mirrors.sjtug.sjtu.edu.cn/bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    restart: always
    network_mode: host
    volumes:
      - ./hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "node-master.lan:9870"
    env_file:
      - ./hadoop.env

  hadoop-namenode:
    image: docker.mirrors.sjtug.sjtu.edu.cn/bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    restart: always
    network_mode: host
    volumes:
      - ./hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=alexchi-cluster
    env_file:
      - ./hadoop.env

  hadoop-historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    restart: always
    network_mode: host
    environment:
      SERVICE_PRECONDITION: "node-master.lan:9000 node-master.lan:9870 node-master.lan:9864 node-1.lan:8088"
    volumes:
      - ./hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env

  hadoop-resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    restart: always
    network_mode: host
    environment:
      SERVICE_PRECONDITION: "node-master.lan:9000 node-master.lan:9870 node-master.lan:9864"
    env_file:
      - ./hadoop.env

  hadoop-nodemanager-0:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    network_mode: host
    restart: always
    environment:
      SERVICE_PRECONDITION: "node-master.lan:9000 node-master.lan:9870 node-master.lan:9864 node-1.lan:8088"
    env_file:
      - ./hadoop.env

  hadoop-nodemanager-1:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    network_mode: host
    restart: always
    environment:
      SERVICE_PRECONDITION: "node-master.lan:9000 node-master.lan:9870 node-master.lan:9864 node-1.lan:8088"
    env_file:
      - ./hadoop.env

  hadoop-nodemanager-2:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    network_mode: host
    restart: always
    environment:
      SERVICE_PRECONDITION: "node-master.lan:9000 node-master.lan:9870 node-master.lan:9864 node-1.lan:8088"
    env_file:
      - ./hadoop.env
